version: "3.8"
services:
  db:
    container_name: postgres 
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=music
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 

volumes:
  db:
